[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_GOOGLE_MAPS_API_KEY,VITE_VAPID_PUBLIC_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
